name: Build, test, and upload code coverage
on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
    branches:
      - main
      - dev
      - test_workflow
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: testCoverage
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./output/reports/coverage/jacoco.xml
          flags: unittests